# https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/html/common-application-properties.html
spring.application.name=mzncvmc
#
# View
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
#
# Messages Setting
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.cache-seconds=-1
#
logging.level.org.springframework.security=DEBUG
#
# Logger
#    1. TRACE: The most detailed log, intended for debugging, outputting almost all events.
#    2. DEBUG: For debugging and flow verification during development.
#    3. INFO: General execution information, typically logged even in production environments.
#    4. WARN: Warning messages, conditions requiring attention.
#    5. ERROR: Critical issues such as error occurrences and exception handling.
#    6. FATAL: Not commonly used by Spring Boot itself, but fatal errors in some logging implementations.
#    7. OFF: Disables log output.
logging.level.root=INFO
logging.level.com.in=DEBUG
#
#logging.level.org.springframework=INFO
#logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#
# Error Page
# Whether to include exception contents in error responses
#server.error.include-exception=TRUE
# Whether to include stack trace contents in error responses (ALWAYS, NEVER, ON_TRACE_PARAM)
#server.error.include-stacktrace=ALWAYS
# Whether to use the default page displayed in server error cases for browser requests
#server.error.whitelabel.enabled=FALSE
#
# MySQL Data Source Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/instudio?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/mzncvmc?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
#
# JPA Properties
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
# SQL 쿼리 출력
#spring.jpa.show-sql=true
#
# SQL 바인딩 파라미터까지 보기
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace
# 콘솔에 로그 레벨 DEBUG 설정
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#
# MyBatis Properties
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.in.mzncvmc.domain
#
# JWT Properties
jwt.secret=VerySecretKeyChangeThisToEnv
jwt.expirationMs=3600000
#
# Pagination Default Setting
app.pagination.default-page=0
app.pagination.default-size=10

